repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=2048"]
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff
        name: "[PY] Ruff"
        args: ["--fix", "--exit-non-zero-on-fix"]

  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        name: "[PY] Black formatter"
        args: ["--target-version", "py313"]

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: "[PY] Isort imports"
